### PR TITLE
Separate finding dogfiles from parsing them; fix #107 and #98

### LINKED ISSUE #98: Ability to specify dogfile dir from the cli
The user can specify a dogfile dir (where Dog will search for a Dogfile, walking up the filesystem from there until one is found) using `-d` or `--directory`. This overrides the default value, which is the current execution directory.

Example:

```
dog -d /path/to/project taskname
```

Please notice that this should also override the workdir to the one where the Dogfile is found (unless the task defines its own workdir)

### LINKED ISSUE #107: Walking up the filesystem fails when a Dogfile is not found
If a Dogfile is not found, Dog shows no output and starts consuming CPU, probably because an infinite for loop.

@marc-gr proposes to stop using `os.Chdir("..")` in a loop and use [filepath's Walk](https://golang.org/pkg/path/filepath/#Walk) instead.

### PR DESCRIPTION
**Pull request by slapresta**
This fixes #107 and separates finding the folder containing the dogfiles by walking up the filesystem from actually parsing said dogfiles. This also implements the `-d`/`--directory` flag (which was trivial after the refactoring) which closes #98.

@xsb @marc-gr @n-marshall thoughts?

### CODE REVIEW

File: cli.go [hunk 1]
```diff
@@ -37,10 +39,11 @@ Dog is a command line application that executes tasks.
 
 Options:
 
-  -i, --info     Print execution info (duration, statuscode) after task execution
-  -w, --workdir  Specify the working directory
-  -h, --help     Print usage information and help
-  -v, --version  Print version information`)
+  -i, --info       Print execution info (duration, statuscode) after task execution
+	-w, --workdir    Specify the working directory
+	-d, --directory  Specify the dogfiles' directory
```
Comment (xsb) [inline cli.go]: Can you fix the indentation here?

File: parser/parser.go [hunk 2]
```diff
@@ -5,13 +5,16 @@ import (
...
+	"path"
+	"path/filepath"
 	"regexp"
 
 	"github.com/dogtools/dog/types"
 	"github.com/ghodss/yaml"
 )
 
 var ErrMalformedStringArray = errors.New("Malformed strings array")
+var ErrNoDogfiles = errors.New("No dogfiles found")
```
Comment (xsb) [inline parser/parser.go]: I'd say "No Dogfile found" here, to keep it consistent with the documentation.

Note: At some point we'll need a way to specify (in errors, in the docs, etc) if we are talking about the file itself or the fact that a folder have 1 multiple Dogfiles that together form a "Dogfile" as defined in the Spec. Both things have the same name now and it's super confusing.

File: cli.go (hunk 1 above)
Comment (slapresta) [inline cli.go]: Sure!

File: parser/parser.go (hunk 2 above)
Comment (slapresta) [inline parser/parser.go]: Agreed! For what it's worth, the string in this error isn't actually displayed to the user at any point.

I agree that it's very confusing at the moment, and the code also makes no effort to differentiate both, as you can see by the `LoadDogFile` function which actually loads several Dogfiles and parses them as a Dogfile. This is even confusing to write about.

Comment (slapresta) [inline parser/parser.go]: I get the feeling that this idea of the different Dogfiles being treated as one comes from when they were literally concatenated together before parsing; I'm not sure how useful it is now.

**Comment by xsb** [comment]
I just tested `-d` and it doesn't work well. The *workdir* needs to be overriden with the path of the provided directory, unless the task specifies another one.

From the issue #98:
> Please notice that this should also override the workdir to the one where the Dogfile is found (unless the task defines its own workdir)

A good way to test if it works is to do:
```
cd $HOME
dog -d $GOPATH/src/github.com/dogtools/dog -i build
```

**Comment by slapresta** [comment]
So, just to be clear, I have implemented it so that the workdir gets assigned by the following rules:

* `-w` has precedence over `workdir:` and `-d`
* `workdir:` has precedence over `-d`

Is this correct? If so, then this should be mergeable now.

**Comment by slapresta** [comment]
I also fixed a null pointer dereference when using `-w` on a task that doesn't exist.
